### ISSUE TITLE
[Linux] Failed to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by Sunderland93** [decaf-emu/decaf-emu#605]
Hello. Building Decaf on Ubuntu 20.04 LTS failed with error:
```
/usr/include/vulkan/vulkan.hpp: In member function 'void vk::DispatchLoaderDynamic::init(const vk::Instance&, const vk::Device&)':
/usr/include/vulkan/vulkan.hpp:70561:18: error: 'DynamicLoader' in namespace 'vk' does not name a type; did you mean 'DynamicState'?
70561 |       static vk::DynamicLoader dl;
      |                  ^~~~~~~~~~~~~
      |                  DynamicState
/usr/include/vulkan/vulkan.hpp:70562:55: error: 'dl' was not declared in this scope
70562 |       PFN_vkGetInstanceProcAddr getInstanceProcAddr = dl.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
      |                                                       ^~
/usr/include/vulkan/vulkan.hpp:70562:98: error: expected primary-expression before '>' token
70562 |       PFN_vkGetInstanceProcAddr getInstanceProcAddr = dl.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
      |                                                                                                  ^
/usr/include/vulkan/vulkan.hpp:70563:92: error: expected primary-expression before '>' token
70563 |       PFN_vkGetDeviceProcAddr getDeviceProcAddr = dl.getProcAddress<PFN_vkGetDeviceProcAddr>("vkGetDeviceProcAddr");
      |                                                                                            ^
make[3]: *** [src/libgpu/CMakeFiles/libgpu.dir/build.make:77: src/libgpu/CMakeFiles/libgpu.dir/cmake_pch.hxx.gch] Error 1
```
